# Generated by Django 2.1.7 on 2019-02-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=100, max_digits=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d')),
            ],
        ),
    ]
