# Generated by Django 2.1.7 on 2019-02-14 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
