# Generated by Django 2.1.7 on 2019-02-14 02:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20190214_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=10, max_digits=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d')),
                ('status', models.BooleanField(default=False)),
                ('posted_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.User', unique=True)),
            ],
        ),
    ]
